name: Gradle real server publish

on:
  push:
    tags:
      - "real"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout server to master
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Checkout submodule to real-server
        uses: actions/checkout@v3
        with:
          token: '${{ secrets.token }}'
          repository: '${{ github.actor }}/${{ secrets.submodule_repository_name }}'
          path: src/main/resources/settings

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build --exclude-task test

      - run: cp ./build/libs/dalda_server-0.0.1-SNAPSHOT.jar ./real-server.jar

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: '${{ secrets.SFTP_USER }}'
          server: '${{ secrets.SFTP_SERVER }}'
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: './real-server.jar'
          remote_path: './jars/temp'
          sftpArgs: '-o ConnectTimeout=5'

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          script: |
            pgrep -of ^java.*real-server.jar$ | xargs kill -9 2> /dev/null
            rm ./jars/real-server.jar 2> /dev/null
            mv ./jars/temp/real-server.jar ./jars/real-server.jar
            nohup java -Dspring.profiles.active=real-server -jar jars/real-server.jar > logs/real-server-log 2>&1 &