name: Gradle dev server publish

on:
  push:
    tags:
      - "dev"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout server to develop
        uses: actions/checkout@v3
        with:
          ref: 'develop'

      - name: Checkout submodule to dev-server
        uses: actions/checkout@v3
        with:
          token: '${{ secrets.token }}'
          repository: '${{ github.actor }}/${{ secrets.submodule_repository_name }}'
          path: src/main/resource/settings
          ref: 'dev-server'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build --exclude-task test

      - run: cp ./build/libs/dalda_server-0.0.1-SNAPSHOT.jar ./dev-server.jar

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: '${{ secrets.SFTP_USER }}'
          server: '${{ secrets.SFTP_SERVER }}'
          ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local_path: './dev-server.jar'
          remote_path: '/home/${{ secrets.SFTP_USER }}/jars/temp'
          sftpArgs: '-o ConnectTimeout=5'

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          script: |
            pgrep -f dev-server | xargs kill -9
            rm ./jars/dev-server.jar
            mv ./jars/temp/dev-server.jar ./jars/dev-server.jar
            nohup java -jar jars/dev-server.jar > logs/dev-server-log 2>&1 &